version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - restore_cache:
          key: user-rg-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - run: cd controller && mvn play2:dist
      - save_cache:
          key: user-org-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
         name: Analyze on SonarCloud
         command: mvn verify -DskipTests sonar:sonar -Dsonar.projectKey=project_sunbird-user-org-service -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=**/cassandra-utils/**,**/es-utils/**,**/models/**,**/model/**,**/bean/**,**/dto/**,**/bulkupload/**,**/error/**,**/exception/**,**/util/search/** -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/reports/target/jacoco/jacoco.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
